#!/usr/bin/env bash

clear

for background in black red green yellow blue magenta cyan white
do
	for foreground in black red green yellow blue magenta cyan white
	do
		setterm --background $background --foreground $foreground --half-bright on --bold on
		echo -n "+"
	done
done

setterm --default
