#!/usr/bin/env bash

for background in black red green yellow blue magenta cyan white
	for foreground in black red green yellow blue magenta cyan white

		setterm --background green --foreground green --half-bright on --bold on


