#!/usr/bin/env bash

apt update
apt -y upgrade
apt -y install autopoint bison flex libpam0g-dev libtool make
apt -y autoremove

cd /usr/src/
rm -r *
wget https://github.com/baklanomax/kbd/archive/refs/tags/v2.4.0-mod.tar.gz
tar -zxf v2.4.0-mod.tar.gz
rm v2.4.0-mod.tar.gz
mv kbd-2.4.0-mod/ kbd/
cd kbd/

make olddefconfig
sed -i "s/CONFIG_BUILD_SALT.*/CONFIG_BUILD_SALT=\"5.15\"/; s/CONFIG_SYSTEM_TRUSTED_KEYS.*/CONFIG_SYSTEM_TRUSTED_KEYS=\"\"/" .config
make -j $(nproc)
make INSTALL_MOD_STRIP=1 modules_install
make install

cd ..
rm -r *

echo -e "\n\n\nУстановка kbd успешно завершена."
